services:
  db:
    image: postgres:15
    container_name: pms_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_conf:/postgres_conf
      - ./postgres_conf/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: pms_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pms
    networks:
      - backend_net

volumes:
  pgdata:

networks:
  backend_net:
